#!/bin/sh
set -euo pipefail

source $(dirname "$0")/"$(echo $_HANDLER | cut -d. -f1).sh"


while true
do
    # Request the next event from the Lambda runtime
    HEADERS="$(mktemp)"
    curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next" -o /tmp/payload

    INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    handler || true

    curl -sS -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$INVOCATION_ID/response" -d "hello from lambda!!!"
done